# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 10563bd0d02b57367996a8d4dd29c44f271d2f670724794dd2ea1be35ecb02d1b45975ee7dd985044e451c6498c788afd19791ccbe2be4c9e18ea1f404035beb

test:
  secret_key_base: 62bf994ffe32982ffaccfc7bfe22d421a3245623917f565f4def8ae37343caf650b6f83596e6076c87985ff987b8ec1e3b68ec93abdc5066e1e153e360b07cd8

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
